export const siteConfig = {
  brand: { name: "Pure Swad", tagline: "Shuddh masala, shuddh swad", logo: "🌿" },
  links: {
    whatsapp: "https://wa.me/910000000000",
    instagram: "https://instagram.com",
  },
  address: "Pure Swad Spices, India",
};

export const products = [
  {
    id: 1,
    slug: "haldi-powder",
    name: "Haldi Powder",
    hindiName: "हल्दी पाउडर",
    image: "",
    tagline: "Sona jaise shuddh haldi",
    shortDesc: "Premium quality turmeric with high curcumin",
    description: "Prachin roop se pis hui shuddh haldi, jo aapke khane ko sona jaisa swarn rang aur sehat deti hai. Immunity badhane aur skin ke liye bhi laabhdayi.",
    benefits: ["High curcumin content", "Boosts immunity naturally", "No additives"],
    price: 149,
    originalPrice: 199,
    weight: "200g",
    inStock: true,
    category: "Single Spice",
  },
  {
    id: 2,
    slug: "lal-mirch-powder",
    name: "Lal Mirch Powder",
    hindiName: "लाल मिर्च पाउडर",
    image: "",
    tagline: "Teez swad, bhari khushboo",
    shortDesc: "Vibrant red chilli powder for authentic heat",
    description: "Bilkul pure lal mirch ka pisa hua masala. Teekha pan aur khaas lal rang jo har sabzi ko dekhne mein bhi swadisht banaye.",
    benefits: ["Natural deep red color", "Perfect heat level", "No artificial color"],
    price: 129,
    originalPrice: 179,
    weight: "200g",
    inStock: true,
    category: "Single Spice",
  },
  {
    id: 3,
    slug: "dhaniya-powder",
    name: "Dhaniya Powder",
    hindiName: "धनिया पाउडर",
    image: "",
    tagline: "Mild swad, meethi khushboo",
    shortDesc: "Fresh coriander powder with sweet aroma",
    description: "Taza dhaniya ka shuddh powder. Halka meetha swad aur sukoon dene wali khushboo jo har sabji aur daal mein jaan daal de.",
    benefits: ["Freshly ground", "Sweet citrusy aroma", "No fillers"],
    price: 119,
    originalPrice: 159,
    weight: "200g",
    inStock: true,
    category: "Single Spice",
  },
  {
    id: 4,
    slug: "jeera-powder",
    name: "Jeera Powder",
    hindiName: "जीरा पाउडर",
    image: "",
    tagline: "Pachan ka dost",
    shortDesc: "Aromatic cumin powder for daily cooking",
    description: "Khushboo se bharpur jeera. Pachan ko behtar banata hai aur har tadka mein ek alag hi swad laata hai.",
    benefits: ["Roasted for deep flavor", "Excellent for digestion", "Rich in iron"],
    price: 139,
    originalPrice: 189,
    weight: "200g",
    inStock: true,
    category: "Single Spice",
  },
  {
    id: 5,
    slug: "garam-masala",
    name: "Garam Masala",
    hindiName: "गरम मसाला",
    image: "",
    tagline: "Dono ka masala, ek dabba",
    shortDesc: "Perfect blend of 12+ aromatic spices",
    description: "Har tarah ke shuddh masalon ka perfect blend. Biryani, paneer, ya kisi bhi special recipe ke liye bas ek chammach kafi hai.",
    benefits: ["Blend of 12+ spices", "Hand-blended", "No MSG"],
    price: 179,
    originalPrice: 249,
    weight: "150g",
    inStock: true,
    category: "Blend",
  },
  {
    id: 6,
    slug: "combo-set",
    name: "Complete Combo Set",
    hindiName: "पूरा स्वाद कॉम्बो",
    image: "",
    tagline: "Saare 5 masale ek saath",
    shortDesc: "All 5 spices in one value pack",
    description: "Pure Swad ke saare 5 signature masale ek premium gift box mein. Ghar ke kitchen ke liye perfect starter pack.",
    benefits: ["All 5 spices", "Save 25%", "Free delivery"],
    price: 599,
    originalPrice: 799,
    weight: "950g total",
    inStock: true,
    category: "Combo",
  },
];

export const categories = [
  { name: "All", filter: "All" },
  { name: "Single Spice", filter: "Single Spice" },
  { name: "Blend", filter: "Blend" },
  { name: "Combo", filter: "Combo" },
];

export const trustCards = [
  { icon: "✅", title: "100% Shuddh", desc: "Koi milawat nahi" },
  { icon: "📋", title: "FSSAI Certified", desc: "Quality standards" },
  { icon: "🌿", title: "Fresh Grinding", desc: "Har batch fresh" },
  { icon: "📦", title: "Airtight Pack", desc: "Swad locked" },
];

export const heroSpices = [
  { name: "Haldi", slug: "haldi-powder", hindi: "हल्दी", image: "/haldipowderherosectionimage.jpeg" },
  { name: "Lal Mirch", slug: "lal-mirch-powder", hindi: "लाल मिर्च", image: "/lalmirchherosectionimage.jpeg" },
  { name: "Dhaniya", slug: "dhaniya-powder", hindi: "धनिया", image: "/dhaniyaherosectionimage.png" },
  { name: "Jeera", slug: "jeera-powder", hindi: "जीरा", image: "/jeeraherosectionimage.jpeg" },
  { name: "Garam Masala", slug: "garam-masala", hindi: "गरम मसाला", image: "/garammashalaherosectionimage.jpeg" },
];