export const siteConfig = {
  brand: { name: "Organic Swaad", tagline: "Pure organic spices, pure organic swad", logo: "🌿" },
  links: {
    whatsapp: "https://wa.me/919759131256",
    instagram: "https://instagram.com",
  },
  address: "Organic Swaad Spices, India",
};

export const products = [
  {
    id: 1,
    slug: "haldi-powder",
    name: "Organic Haldi Powder",
    hindiName: "हल्दी पाउडर",
    image: "/organicswaadproducthaldipowder.jpeg",
    tagline: "Sona jaise shuddh organic haldi",
    shortDesc: "Premium quality organic turmeric with high curcumin content",
    description: "Khas organic farming se ughaya gya shuddh haldi ka powder, jo aapke khane ko sona jaisa swarn rang aur sehat deta hai. immunity badhane, skin ke liye aur heart health ke liye bhi laabhdayi.",
    benefits: ["High curcumin content", "Organic farming", "100% chemical-free"],
    price: 179,
    originalPrice: 249,
    weight: "200g",
    inStock: true,
    category: "Single Spice",
  },
  {
    id: 2,
    slug: "lal-mirch-powder",
    name: "Organic Lal Mirch Powder",
    hindiName: "लाल मिर्च पाउडर",
    image: "/organicswaadproductmirchipowder.jpeg",
    tagline: "Teez swad, bhari khusboo, pure organic",
    shortDesc: "Vibrant red organic chilli powder for authentic heat without artificial additives",
    description: "Pure organic lal mirch ka pisa hua powder. Teekha pan aur khaas lal rang jo har sabzi ko dekhne mein bhi swadisht banaye - bina kisi chemical ke.",
    benefits: ["Natural deep red color", "Organic farming", "No artificial colors or preservatives"],
    price: 149,
    originalPrice: 199,
    weight: "200g",
    inStock: true,
    category: "Single Spice",
  },
  {
    id: 3,
    slug: "dhaniya-powder",
    name: "Organic Dhaniya Powder",
    hindiName: "धनिया पाउडर",
    image: "/organicswaadproductimagedhaniyapowder.jpeg",
    tagline: "Mild swad, meethi khusboo, pure organic",
    shortDesc: "Fresh organic coriander powder with sweet aroma, grown without pesticides",
    description: "Organic farm se laye gye taza dhaniya ka shuddh powder. Halka meetha swad aur sukoon dene wali khusboo jo har sabji aur daal mein jaan daal de - pure organic.",
    benefits: ["Freshly ground", "Organic farming", "No synthetic fertilizers"],
    price: 139,
    originalPrice: 179,
    weight: "200g",
    inStock: true,
    category: "Single Spice",
  },
  {
    id: 4,
    slug: "jeera-powder",
    name: "Organic Jeera Powder",
    hindiName: "जीरा पाउडर",
    image: "/organicswaadproductjeerapowder.jpeg",
    tagline: "Pachan ka dost, pure organic",
    shortDesc: "Aromatic organic cumin powder for daily cooking without chemicals",
    description: "Organic farming se ughaya gya khushboo se bharpur jeera. Pachan ko behtar banata hai aur har tadka mein ek alag hi swad laata hai - pure organic.",
    benefits: ["Organic roasted for deep flavor", "Excellent for digestion", "Rich in iron", "No chemical residues"],
    price: 149,
    originalPrice: 199,
    weight: "200g",
    inStock: true,
    category: "Single Spice",
  },
  {
    id: 5,
    slug: "garam-masala",
    name: "Organic Garam Masala",
    hindiName: "गरम मसाला",
    image: "/organicswaadproductgarammashala.jpeg",
    tagline: "Dono ka masala, ek dabba - pure organic",
    shortDesc: "Perfect blend of 12+ aromatic spices from organic farms",
    description: "Har tarah ke organic masalon ka perfect blend. Biryani, paneer, ya kisi bhi special recipe ke liye bas ek chammach kafi hai - bina kisi milawat ke.",
    benefits: ["Blend of 12+ organic spices", "Hand-blended", "FSSAI certified", "No MSG or artificial additives"],
    price: 199,
    originalPrice: 279,
    weight: "150g",
    inStock: true,
    category: "Blend",
  },
  {
    id: 6,
    slug: "combo-set",
    name: "Complete Organic Combo Set",
    hindiName: "पूरा स्वाद कॉम्बो",
    image: "/organicswaadproducthaldipowder.jpeg",
    tagline: "Saare 5 organic masale ek saath",
    shortDesc: "All 5 organic spices in one value pack with free delivery",
    description: "Organic Swaad ke saare 5 signature organic masale ek premium gift box mein. Ghar ke kitchen ke liye perfect starter pack.",
    benefits: ["All 5 organic spices", "Save 30%", "Free delivery", "Eco-friendly packaging"],
    price: 749,
    originalPrice: 999,
    weight: "950g total",
    inStock: true,
    category: "Combo",
  },
];

export const categories = [
  { name: "All", filter: "All" },
  { name: "Single Spice", filter: "Single Spice" },
  { name: "Blend", filter: "Blend" },
  { name: "Combo", filter: "Combo" },
];

export const trustCards = [
  { icon: "✅", title: "100% Organic", desc: "Koi chemical nahi" },
  { icon: "📋", title: "FSSAI Certified", desc: "Quality standards" },
  { icon: "🌱", title: "Organic Farming", desc: "Sustainable methods" },
  { icon: "💚", title: "Chemical-Free", desc: "Pure organic" },
];

export const heroSpices = [
  { name: "Haldi", slug: "haldi-powder", hindi: "हल्दी", image: "/organicswaadslide1.jpeg" },
  { name: "Lal Mirch", slug: "lal-mirch-powder", hindi: "लाल मिर्च", image: "/organicswaadslide2.jpeg" },
  { name: "Dhaniya", slug: "dhaniya-powder", hindi: "धनिया", image: "/organicswaadslide3.jpeg" },
  { name: "Jeera", slug: "jeera-powder", hindi: "जीरा", image: "/organicswaadslide4.jpeg" },
  { name: "Garam Masala", slug: "garam-masala", hindi: "गरम मसाला", image: "/orgnicswaadslide5.jpeg" },
];